"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import Navbar from "../component/Navbar";


const inter = Inter({ subsets: ["latin"] });

{/** 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/}
export default function RootLayout({ children }) {
   useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
       <Navbar/> 
        {children}</body>
    </html>
  );
}
